export const DATABASE_LOAD_FAILED = 'FILE_MANAGER/DATABASE_LOAD_FAILED';
export const DATABASE_LOAD_INIT = 'FILE_MANAGER/DATABASE_LOAD_INIT';
export const DATABASE_LOAD_SUCCESS = 'FILE_MANAGER/DATABASE_LOAD_SUCCESS';

export const FILE_LOAD_FAILED = 'FILE_MANAGER/FILE_LOAD_FAILED';
export const FILE_LOAD_INIT = 'FILE_MANAGER/FILE_LOAD_INIT';
export const FILE_LOAD_SUCCESS = 'FILE_MANAGER/FILE_LOAD_SUCCESS';

export const SELECT_FILE = 'FILE_MANAGER/SELECT_FILE';
