export const FILE_LOADED_SUCCESS = 'FILE_MANAGER/FILE_LOADED_SUCCESS';

export const DATABASE_LOAD_FAILED = 'FILE_MANAGER/DATABASE_LOAD_FAILED';
export const DATABASE_LOAD_INIT = 'FILE_MANAGER/DATABASE_LOAD_INIT';
export const DATABASE_LOAD_SUCCESS = 'FILE_MANAGER/DATABASE_LOAD_SUCCESS';
